{
 "title": "Services",
 "tags": [ "datalayer" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "logs_source", "label": "Logs source", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "ai-agents, iam, jupyter, jupyter-companion, library, operator, spacer"
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_method, http_route) (http_server_duration_milliseconds_count{service_name=\"$service_name\"})",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_milliseconds_sum{service_name=\"$service_name\"} / http_server_duration_milliseconds_count{service_name=\"$service_name\"}",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{service_name=\"$service_name\",http_status_code=~\"5..\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\",http_status_code=~\"2..\"}) / sum by(http_route, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\"})",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\",http_status_code=~\"5..\"}) / sum by(http_route, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\"})",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_duration_milliseconds_bucket{service_name=\"$service_name\"}[1m])) by(http_route, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "http_server_active_requests{service_name=\"$service_name\"}",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[10m])",
     "legendFormat": "{{http_method}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(type) (rate({service_name=\"$service_name\"} | pattern `<date> <time> <type> <logger> <code> [trace_id=<trace_id> span_id=<span_id> resource.service.name=<service_name> <_>] - <msg>` | type != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\"} | pattern `<date> <time> <type> <logger> <code> [trace_id=<trace_id> span_id=<span_id> resource.service.name=<service_name> <_>] - <msg>` | line_format \"{{.service_name}}\\t{{.type}}\\t trace_id={{.trace_id}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}